version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: my_email_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # Mot de passe root
      MYSQL_DATABASE: email_sender  # Base de données initiale à créer
      MYSQL_USER: email_user  # Utilisateur
      MYSQL_PASSWORD: emailpass  # Mot de passe utilisateur
    ports:
      - "5433:3306"    
    volumes:
      - db_data:/var/lib/mysql  # Volume persistant pour les données de MySQL

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mail_nextjs
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mail_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql

volumes:
  db_data: